from pathlib import Path

from docx import Document
from docx.shared import Pt


ROOT = Path(r"C:/Users/TonyTang/Documents/chan.py")
REFERENCE = Path(r"C:/Users/TonyTang/Desktop/word/5分钟模型.docx")
OUT = ROOT / "BSP回测策略代码说明.docx"


PARAGRAPHS = [
    "这段代码用于创建并回测一个基于缠论买卖点（BSP）的交易策略。整体流程包括：创建BSP策略、设置风险管理、设置回测参数、运行回测、输出交易结果和资金曲线。",
    "代码中的核心策略是 SegBspStrategy。它不是机器学习模型，而是一套规则型交易逻辑。它根据当前线段方向、BSP类型、买入信号数量、卖出信号数量和结构变化来决定是否开仓或平仓。",
    "一、导入模块",
    "from CustomBuySellPoint import SegBspStrategy, SegBspStrategyConfig",
    "这里导入的是BSP策略类和策略配置类。",
    "SegBspStrategy：真正执行买卖点策略判断的类。",
    "SegBspStrategyConfig：用来定义策略参数，例如允许哪些BSP类型、需要多少个信号、回看多少根K线等。",
    "from ModelStrategy import BacktestChanConfig, run_bsp_backtest",
    "这里导入的是回测配置和回测执行函数。",
    "BacktestChanConfig：定义回测资金、手续费、滑点、是否在结束时平仓等参数。",
    "run_bsp_backtest：把价格数据、BSP数据、策略和风控规则放在一起执行回测。",
    "from Trade import RiskConfig, RiskManager",
    "这里导入的是风险控制模块。",
    "RiskConfig：定义止损、止盈、移动止损、最长持仓时间等风控参数。",
    "RiskManager：在回测过程中根据 RiskConfig 判断是否需要强制退出。",
    "二、创建策略",
    "strategy = SegBspStrategy(SegBspStrategyConfig(...))",
    "这一部分创建了一个基于线段方向和BSP类型的交易策略。",
    "entry_segment_directions=frozenset({'up', 'down'})",
    "这表示策略允许在上行线段和下行线段中都寻找买入机会。",
    "up：当前结构处于上行线段。",
    "down：当前结构处于下行线段。",
    "策略虽然允许两个方向都进场，但对 up 和 down 的要求不同。up 段买入更像顺势交易，down 段买入更像逆势反弹交易。",
    "entry_bsp_types=frozenset({'1','1p','2','2s','3a','3b'})",
    "这表示这些BSP类型都可以作为买入信号来源。",
    "1：一类买卖点。",
    "1p：类一买卖点。",
    "2：二类买卖点。",
    "2s：二类延伸或次级二买/二卖。",
    "3a：三类买卖点中的一种结构。",
    "3b：三类买卖点中的另一种结构。",
    "sell_bsp_types=frozenset({'1','1p','2','2s','3a','3b'})",
    "这表示这些BSP类型也都可以作为卖出或退出信号来源。",
    "三、买入回看窗口",
    "buy_lookback_bars_by_segment={'up': 10, 'down': 15}",
    "这个参数表示在判断是否可以买入时，系统会向前回看多少根K线内出现的BSP买入信号。",
    "up: 10 表示如果当前是上行线段，只看最近10根K线内的买入信号。",
    "down: 15 表示如果当前是下行线段，会看最近15根K线内的买入信号。",
    "下行线段的回看窗口更长，因为逆势机会可能需要更多时间累积信号确认。",
    "四、不同线段下的买入信号要求",
    "required_buy_signals_by_segment 用来定义不同线段方向、不同BSP类型分别需要多少个买入信号才允许开仓。",
    "在 up 段中，所有BSP类型都只需要1个买入信号。",
    "这代表顺势买入逻辑：当市场结构已经在上行段中，只要出现一个有效BSP买入信号，就可以进场。",
    "在 down 段中，1、1p、2、2s 类型需要5个买入信号。",
    "在 down 段中，3a 和 3b 类型需要10个买入信号。",
    "这代表逆势买入逻辑：当市场结构仍处于下行段时，不能因为一个信号就直接买入，需要更多BSP信号重复确认。",
    "3a 和 3b 在 down 段中要求10个信号，说明这类逆势结构被认为风险更高，需要更强确认。",
    "五、卖出回看窗口",
    "sell_lookback_bars_by_entry_segment={'up': 20, 'down': 10}",
    "这个参数不是根据当前线段决定，而是根据开仓时的线段方向决定。",
    "如果仓位是在 up 段中开的，卖出时回看20根K线。",
    "如果仓位是在 down 段中开的，卖出时回看10根K线。",
    "up 段开仓属于顺势交易，因此允许更长时间观察，不轻易退出。",
    "down 段开仓属于逆势交易，因此退出判断更快，防止反弹失败后继续持仓。",
    "六、不同开仓线段下的卖出信号要求",
    "required_sell_signals_by_entry_segment 用来定义开仓以后，需要多少个卖出信号才退出。",
    "如果仓位是在 up 段中开的，所有BSP类型都需要15个卖出信号才退出。",
    "这表示顺势仓位会被允许持有更久，不因为少量卖出信号就过早离场。",
    "如果仓位是在 down 段中开的，所有BSP类型只需要1个卖出信号就退出。",
    "这表示逆势仓位退出非常敏感。只要出现一个卖出信号，就认为反弹可能失败，应尽快离场。",
    "七、结构性退出",
    "exit_segment_directions_by_entry_segment={'up': frozenset({'down'}), 'down': frozenset()}",
    "这个参数定义了线段结构变化时是否需要退出。",
    "如果仓位是在 up 段中开的，当结构转为 down 时退出。",
    "这说明顺势多头仓位依赖上行结构。一旦结构转弱，就触发结构性退出。",
    "如果仓位是在 down 段中开的，exit_segment_directions 为空。",
    "这说明 down 段逆势仓位不通过线段方向变化直接退出，而主要依赖卖出信号和风控规则退出。",
    "八、全局默认参数",
    "required_buy_signals=1",
    "这是买入信号数量的默认值。当具体 segment/type 没有配置时使用。",
    "buy_lookback_bars=15",
    "这是买入回看K线数量的默认值。",
    "required_sell_signals=5",
    "这是卖出信号数量的默认值。",
    "sell_lookback_bars=10",
    "这是卖出回看K线数量的默认值。",
    "这些全局参数是 fallback values。优先级低于前面按 segment 单独配置的参数。",
    "九、其他策略行为参数",
    "exit_on_down_segment=True",
    "表示当结构进入下行段时，可以触发退出逻辑。实际退出还会结合 exit_segment_directions_by_entry_segment。",
    "allow_unconfirmed_entry=False",
    "表示不允许使用未确认信号开仓。这样可以减少信号尚未稳定时进场造成的噪音。",
    "reset_sell_count_on_buy=True",
    "表示出现买入动作后，卖出信号计数会重置。",
    "reset_buy_count_on_sell=True",
    "表示出现卖出动作后，买入信号计数会重置。",
    "position_fraction=1.0",
    "表示每次开仓使用100%的可用资金或策略允许资金比例。",
    "十、风险管理",
    "risk_manager = RiskManager(RiskConfig(...))",
    "这一部分设置交易风险控制。即使BSP策略没有发出卖出信号，RiskManager 也可以根据风险规则强制退出。",
    "stop_loss_pct=0.03",
    "表示亏损达到3%时止损。",
    "take_profit_pct=0.20",
    "表示盈利达到20%时止盈。",
    "trailing_stop_pct=0.025",
    "表示使用2.5%的移动止损。价格先向有利方向移动以后，如果从高点回撤超过2.5%，就触发退出。",
    "max_holding_bars=78 * 10",
    "表示最长持仓780根K线。如果是5分钟K线，一个交易日大约78根K线，因此这里约等于最长持仓10个交易日。",
    "十一、回测配置",
    "backtest_config = BacktestChanConfig(...)",
    "这一部分定义回测环境参数。",
    "initial_capital=100_000",
    "初始资金为100,000。",
    "fee_pct=0.000",
    "手续费为0。",
    "slippage_pct=0.000",
    "滑点为0。",
    "close_at_end=True",
    "回测结束时，如果仍有持仓，则强制平仓，保证最终结果完整。",
    "十二、运行回测",
    "result = run_bsp_backtest(price_df=price_df, bsp_df=bsp_df, strategy=strategy, config=backtest_config, risk_manager=risk_manager)",
    "这一行真正执行回测。",
    "price_df：价格K线数据。",
    "bsp_df：已经计算好的缠论买卖点数据。",
    "strategy：前面创建的BSP交易策略。",
    "config：回测资金、手续费、滑点和结束平仓规则。",
    "risk_manager：止损、止盈、移动止损和最长持仓规则。",
    "run_bsp_backtest 会按时间顺序读取价格和BSP信号，判断是否开仓、平仓，并记录每笔交易和每日资金变化。",
    "十三、输出结果",
    "print('\\nStrategy metrics:')",
    "这会打印策略表现指标标题。",
    "for name, value in result.metrics.items(): print(f'{name}: {value}')",
    "这会逐项打印回测指标，例如收益率、最大回撤、胜率、交易次数等。具体指标取决于 result.metrics 中保存了哪些字段。",
    "print('\\nTrade count:', len(result.trades))",
    "这会打印总交易次数。",
    "display(result.trades)",
    "这会在 notebook 中展示所有交易记录。",
    "display(result.equity.tail())",
    "这会展示资金曲线最后几行，用来看最终资金状态。",
    "十四、结果分析",
    "结果文件来自 outputs/strategy_backtest/TQQQ_5m_strategy_result.xlsx。",
    "总体表现非常强，但风险也明显。",
    "初始资金为100,000，最终资金 final_equity 为15,166,253.46。",
    "total_return 为150.66，表示资金增长约150.66倍。",
    "max_drawdown 为-26.32%，说明策略历史最大回撤约为26.32%。这个回撤不算小，说明虽然长期收益高，但资金曲线中存在明显风险阶段。",
    "sharpe 为1.68，说明风险调整后收益较好，但还不是完全平滑的低风险曲线。",
    "closed_trades 为1011笔，样本数量较多，结果不是由极少数交易构成。",
    "win_rate 为58.06%，说明胜率高于50%，但不是特别高。策略收益主要来自盈利交易平均质量和趋势阶段复利，而不是单纯靠极高胜率。",
    "profit_factor 为1.64，表示总盈利约为总亏损的1.64倍。这个值为正向，但仍说明亏损交易对结果有较大影响。",
    "从年份看，所有年份的净利润都是正的。",
    "2020年净利润约290,483，交易139笔，胜率64.75%。",
    "2021年净利润约254,430，交易142笔，胜率59.15%。",
    "2022年净利润约745,527，交易218笔，胜率50.46%。",
    "2023年净利润约1,016,252，交易143笔，胜率58.04%。",
    "2024年净利润约3,554,027，交易157笔，胜率58.60%。",
    "2025年净利润约6,442,743，交易148笔，胜率62.84%。",
    "2026年至5月29日净利润约2,762,792，交易64笔，胜率54.69%。",
    "2024和2025是收益贡献最大的年份，说明策略在这两年TQQQ行情中非常有效。",
    "2022年的交易数最多，为218笔，但胜率只有50.46%，说明震荡或下跌环境中信号噪音更高，交易效率下降。",
    "换算成年收益率后，可以更清楚地比较每一年策略的资金增长效率。",
    "2020年策略收益率约290.48%，同期TQQQ买入持有收益率约106.13%。",
    "2021年策略收益率约65.16%，同期TQQQ买入持有收益率约80.12%。",
    "2022年策略收益率约115.60%，同期TQQQ买入持有收益率约-79.32%。",
    "2023年策略收益率约73.74%，同期TQQQ买入持有收益率约182.27%。",
    "2024年策略收益率约145.48%，同期TQQQ买入持有收益率约56.08%。",
    "2025年策略收益率约106.91%，同期TQQQ买入持有收益率约30.65%。",
    "2026年至5月29日，策略收益率约19.30%，同期TQQQ买入持有收益率约55.33%。",
    "从年度收益率比较看，策略在2020、2022、2024和2025明显跑赢TQQQ买入持有。",
    "2022年的差异尤其重要：TQQQ买入持有大幅亏损约79.32%，但策略仍取得约115.60%的正收益，说明这套BSP交易规则在熊市或高波动环境中有较强的主动交易优势。",
    "策略在2021、2023和2026年至5月29日低于买入持有，说明在强单边上涨环境中，频繁进出可能不如长期持有TQQQ。",
    "因此这套策略的主要优势不是始终追上最强趋势，而是在高波动或下跌年份中控制风险并捕捉阶段性交易机会。",
    "从开仓线段看，down段开仓有764笔，up段开仓有247笔。",
    "down段交易数量更多，但净利润约4,482,835，平均单笔收益率约0.20%，胜率约53.93%。",
    "up段交易数量更少，但净利润约10,583,420，平均单笔收益率约1.55%，胜率约70.85%。",
    "这说明策略真正的主要利润来源是up段顺势交易，而不是down段逆势反弹。",
    "down段规则虽然贡献了交易机会和部分收益，但效率明显低于up段。",
    "如果要优化策略，应该重点检查down段入场是否过多，因为它占交易数量大部分，但单位收益和胜率都更弱。",
    "从退出原因看，trailing_stop 是最多的退出方式，共422笔。",
    "但是 trailing_stop 的总净利润约为-8,803,941，平均收益率约-0.47%，胜率只有30.81%。",
    "这说明当前移动止损并不是主要利润来源，反而在很多交易中承担了亏损或回撤后的退出功能。",
    "entry segment up; exit segment down 有144笔，总净利润约8,806,362，胜率81.25%。",
    "这说明up段开仓后，当结构转为down再退出，是非常重要的盈利退出机制。",
    "1/1 type-1 sell-signal bars in 10-bar window in current up segment 有131笔，总净利润约13,761,080，胜率100%。",
    "这是结果中最强的退出路径之一，说明在up segment中的type-1卖出信号对锁定利润非常有效。",
    "1/1 type-3a sell-signal bars in 10-bar window in current up segment 有124笔，总净利润约1,359,535，胜率68.55%。",
    "stop_loss 有35笔，总净利润约-4,642,656，胜率0%。",
    "stop_loss 的数量不多，但亏损金额很大，说明少数止损交易对整体回撤影响明显。",
    "take_profit 只有1笔，max_holding_bars 也只有1笔。",
    "这说明固定止盈和最长持仓并不是主要退出方式，策略主要依靠BSP卖出信号、结构退出和移动止损完成退出。",
    "从单笔收益分布看，平均 return_pct 为0.53%，中位数为0.37%。",
    "25分位数为-1.30%，75分位数为1.72%。",
    "5分位数为-2.80%，95分位数为5.28%。",
    "最大单笔收益为20.03%，最差单笔亏损为-9.18%。",
    "这说明策略大多数交易是短线小收益或小亏损，但偶尔会出现较大的盈利和亏损。",
    "从持仓时间看，平均持仓约13.75小时，中位数约3.5小时。",
    "75%的交易持仓时间小于约16.83小时，95%的交易小于约67小时。",
    "最长持仓约145.75小时。",
    "这说明策略整体偏短线，大部分交易在日内或隔夜短周期内完成，但也保留少量多日持仓。",
    "资金曲线方面，最终资金为15,166,253.46，历史最高资金约15,564,990.64。",
    "最深回撤发生在2022-04-26 16:05:00，当时资金约650,063.97，drawdown_pct 为-26.32%。",
    "这说明2022年虽然最后全年仍盈利，但过程中出现过明显回撤，可能是策略在震荡或快速反转行情中的主要压力阶段。",
    "总体结论是：策略长期收益非常强，且样本量充足，但收益主要来自up段顺势交易和部分高质量BSP卖出退出。",
    "主要风险来自down段大量交易的低效率、trailing_stop退出的负贡献，以及少数stop_loss交易造成的大额亏损。",
    "下一步优化方向可以考虑：减少down段逆势开仓、重新测试trailing_stop参数、限制stop_loss单笔损失、并单独保留或强化up段顺势交易逻辑。",
    "十五、这套策略的核心逻辑",
    "这套策略的核心思想是：顺势交易更容易进场、更慢退出；逆势交易更难进场、更快退出。",
    "在 up 段中，只要出现一个买入BSP信号就可以开仓，因为当前结构已经支持上涨。",
    "在 down 段中，需要多个买入BSP信号才可以开仓，因为这是逆势反弹交易，风险更高。",
    "在 up 段开仓后，需要很多卖出信号或结构转弱才退出，目的是让趋势利润继续运行。",
    "在 down 段开仓后，只要出现一个卖出信号就退出，目的是快速保护逆势仓位。",
    "风险管理层独立于BSP逻辑存在。即使结构信号没有触发退出，只要达到止损、止盈、移动止损或最长持仓限制，也会退出。",
    "十六、可以关注的参数影响",
    "down 段 required_buy_signals 越高，逆势交易越少，但信号质量可能更高。",
    "up 段 required_sell_signals 越高，顺势仓位持有越久，但回撤可能更大。",
    "trailing_stop_pct 越小，利润保护越紧，但也更容易被正常波动洗出。",
    "max_holding_bars 越短，交易更偏短线；越长，策略越允许等待趋势延续。",
    "stop_loss_pct 越小，单笔亏损控制越严格，但也更容易提前止损。",
]


def clear_paragraph(paragraph):
    p = paragraph._p
    for child in list(p):
        p.remove(child)


def set_paragraph(paragraph, text):
    clear_paragraph(paragraph)
    run = paragraph.add_run(text)
    run.bold = True
    run.font.size = Pt(11)


def main():
    doc = Document(str(REFERENCE))
    body = doc._body._element
    paragraphs = doc.paragraphs

    while len(paragraphs) < len(PARAGRAPHS):
        doc.add_paragraph()
        paragraphs = doc.paragraphs

    for i, text in enumerate(PARAGRAPHS):
        set_paragraph(paragraphs[i], text)

    for paragraph in paragraphs[len(PARAGRAPHS):]:
        body.remove(paragraph._element)

    doc.save(str(OUT))
    print(OUT)


if __name__ == "__main__":
    main()
